
package introsde.business.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import introsde.adapter.ws.Exercise;
import introsde.localdatabase.soap.Measure;
import introsde.localdatabase.soap.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Business", targetNamespace = "http://ws.business.introsde/")
@XmlSeeAlso({
    introsde.localdatabase.soap.ObjectFactory.class,
    introsde.adapter.ws.ObjectFactory.class,
    introsde.business.ws.ObjectFactory.class
})
public interface Business {


    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.CreatePersonResponse")
    @Action(input = "http://ws.business.introsde/Business/createPersonRequest", output = "http://ws.business.introsde/Business/createPersonResponse")
    public void createPerson(
        @WebParam(name = "person", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Person> person);

    /**
     * 
     * @param measure
     * @param chatId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "measure", targetNamespace = "")
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SavePersonMeasureResponse")
    @Action(input = "http://ws.business.introsde/Business/savePersonMeasureRequest", output = "http://ws.business.introsde/Business/savePersonMeasureResponse")
    public String savePersonMeasure(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId,
        @WebParam(name = "measure", targetNamespace = "")
        Measure measure);

    /**
     * 
     * @param chatId
     * @return
     *     returns introsde.localdatabase.soap.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "getProfile", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetProfile")
    @ResponseWrapper(localName = "getProfileResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetProfileResponse")
    @Action(input = "http://ws.business.introsde/Business/getProfileRequest", output = "http://ws.business.introsde/Business/getProfileResponse")
    public Person getProfile(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId);

    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.UpdatePersonResponse")
    @Action(input = "http://ws.business.introsde/Business/updatePersonRequest", output = "http://ws.business.introsde/Business/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "person", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Person> person);

    /**
     * 
     * @param chatId
     * @param exercise
     * @return
     *     returns introsde.adapter.ws.Exercise
     */
    @WebMethod
    @WebResult(name = "calories", targetNamespace = "")
    @RequestWrapper(localName = "getCalories", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetCalories")
    @ResponseWrapper(localName = "getCaloriesResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetCaloriesResponse")
    @Action(input = "http://ws.business.introsde/Business/getCaloriesRequest", output = "http://ws.business.introsde/Business/getCaloriesResponse")
    public Exercise getCalories(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId,
        @WebParam(name = "exercise", targetNamespace = "")
        Exercise exercise);

    /**
     * 
     * @param hours
     * @param chatId
     */
    @WebMethod
    @RequestWrapper(localName = "setSleepTime", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SetSleepTime")
    @ResponseWrapper(localName = "setSleepTimeResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SetSleepTimeResponse")
    @Action(input = "http://ws.business.introsde/Business/setSleepTimeRequest", output = "http://ws.business.introsde/Business/setSleepTimeResponse")
    public void setSleepTime(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId,
        @WebParam(name = "hours", targetNamespace = "")
        double hours);

    /**
     * 
     * @param chatId
     * @return
     *     returns introsde.adapter.ws.Exercise
     */
    @WebMethod
    @WebResult(name = "exercise", targetNamespace = "")
    @RequestWrapper(localName = "getExercise", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetExercise")
    @ResponseWrapper(localName = "getExerciseResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetExerciseResponse")
    @Action(input = "http://ws.business.introsde/Business/getExerciseRequest", output = "http://ws.business.introsde/Business/getExerciseResponse")
    public Exercise getExercise(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId);

    /**
     * 
     * @param chatId
     * @return
     *     returns java.util.List<introsde.adapter.ws.Exercise>
     */
    @WebMethod
    @WebResult(name = "exercises", targetNamespace = "")
    @RequestWrapper(localName = "getTodayExercises", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetTodayExercises")
    @ResponseWrapper(localName = "getTodayExercisesResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetTodayExercisesResponse")
    @Action(input = "http://ws.business.introsde/Business/getTodayExercisesRequest", output = "http://ws.business.introsde/Business/getTodayExercisesResponse")
    public List<Exercise> getTodayExercises(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId);

    /**
     * 
     * @param chatId
     * @param recipeId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSentenceRecipeCalories", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetSentenceRecipeCalories")
    @ResponseWrapper(localName = "getSentenceRecipeCaloriesResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.GetSentenceRecipeCaloriesResponse")
    @Action(input = "http://ws.business.introsde/Business/getSentenceRecipeCaloriesRequest", output = "http://ws.business.introsde/Business/getSentenceRecipeCaloriesResponse")
    public String getSentenceRecipeCalories(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId,
        @WebParam(name = "recipeId", targetNamespace = "")
        Integer recipeId);

}
