
package introsde.business.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import introsde.localdatabase.soap.Measure;
import introsde.localdatabase.soap.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Business", targetNamespace = "http://ws.business.introsde/")
@XmlSeeAlso({
    introsde.localdatabase.soap.ObjectFactory.class,
    introsde.business.ws.ObjectFactory.class
})
public interface Business {


    /**
     * 
     * @param person
     */
    @WebMethod
    @RequestWrapper(localName = "createPerson", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.CreatePerson")
    @ResponseWrapper(localName = "createPersonResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.CreatePersonResponse")
    @Action(input = "http://ws.business.introsde/Business/createPersonRequest", output = "http://ws.business.introsde/Business/createPersonResponse")
    public void createPerson(
        @WebParam(name = "person", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Person> person);

    /**
     * 
     * @param measure
     * @param chatId
     */
    @WebMethod
    @RequestWrapper(localName = "savePersonMeasure", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SavePersonMeasure")
    @ResponseWrapper(localName = "savePersonMeasureResponse", targetNamespace = "http://ws.business.introsde/", className = "introsde.business.ws.SavePersonMeasureResponse")
    @Action(input = "http://ws.business.introsde/Business/savePersonMeasureRequest", output = "http://ws.business.introsde/Business/savePersonMeasureResponse")
    public void savePersonMeasure(
        @WebParam(name = "chatId", targetNamespace = "")
        Long chatId,
        @WebParam(name = "measure", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Measure> measure);

}
